---
- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install multiple packages
  community.general.flatpak:
    name:
      - com.bluejeans.BlueJeans
      - com.dropbox.Client
      - com.obsproject.Studio
      - com.spotify.Client
      - org.telegram.desktop
      - org.videolan.VLC
      - org.qbittorrent.qBittorrent
      - org.libreoffice.LibreOffice
      - im.riot.Riot